import mongoose, { Schema, Document } from "mongoose";

export interface IBooking extends Document {
  user: mongoose.Types.ObjectId;
  court: mongoose.Types.ObjectId;

  date: string;        // YYYY-MM-DD
  startTime: string;   // HH:mm
  endTime: string;     // HH:mm
  price: number;

  // booking lifecycle
  status: "pending" | "confirmed" | "cancelled" | "completed";

  // payment info (eSewa)
  paymentMethod: "NONE" | "ESEWA";
  paymentStatus: "UNPAID" | "PAID" | "FAILED";
  transactionUuid?: string;     // generated by us
  transactionCode?: string;     // returned by eSewa
  paidAt?: Date;
}

const BookingSchema = new Schema<IBooking>(
  {
    user: { type: Schema.Types.ObjectId, ref: "User", required: true },
    court: { type: Schema.Types.ObjectId, ref: "Court", required: true },

    date: { type: String, required: true },
    startTime: { type: String, required: true },
    endTime: { type: String, required: true },
    price: { type: Number, required: true },

    status: {
      type: String,
      enum: ["pending", "confirmed", "cancelled", "completed"],
      default: "pending",
    },

    paymentMethod: {
      type: String,
      enum: ["NONE", "ESEWA"],
      default: "NONE",
    },
    paymentStatus: {
      type: String,
      enum: ["UNPAID", "PAID", "FAILED"],
      default: "UNPAID",
    },
    transactionUuid: { type: String },
    transactionCode: { type: String },
    paidAt: { type: Date },
  },
  { timestamps: true }
);

export const BookingModel = mongoose.model<IBooking>("Booking", BookingSchema);